services:
  svc1:
    build: ./svc1
    ports:
      - "8000:8000"
  svc2:
    build: ./svc2
    ports:
      - "8002:8001"
  prometheus:
    image: prom/prometheus
    volumes:
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/alert.rules.yaml:/etc/prometheus/alert.rules.yaml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  alertmanager:
    image: prom/alertmanager
    volumes:
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
    ports:
      - "9093:9093"
