version: '3.8'

services:
  svc1:
    build: ./svc1
    ports:
      - "8000:8000"

  svc2:
    build: ./svc2
    ports:
      - "8002:8001"

  ruby_app:
    build: ./ruby_app
    volumes:
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/ruby_app/logs:/var/log/ruby_app
    ports:
      - "4567:4567"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  prometheus:
    image: prom/prometheus
    volumes:
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/alert.rules.yaml:/etc/prometheus/alert.rules.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  alertmanager:
    image: prom/alertmanager
    volumes:
      - /c/Users/haoha/OneDrive/Desktop/personal/Projects/Personal/Hackathons/Building Blocs June Conference 2024/LDSS/svc/alertmanager.yaml:/etc/alertmanager/alertmanager.yaml
    ports:
      - "9093:9093"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.2
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.2
    user: root
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yaml:ro
    depends_on:
      - logstash

volumes:
  esdata:
    driver: local
