global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'svc1'
    static_configs:
      - targets: ['svc1:8000']

  - job_name: 'svc2'
    static_configs:
      - targets: ['svc2:8001']

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']
