global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'streamlit_app'
    static_configs:
      - targets: ['host.docker.internal:8000']
  
  - job_name: 'ruby_app'
    static_configs:
      - targets: ['host.docker.internal:4567']

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']
